# Generated by Django 4.1.6 on 2023-02-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_tache_task_tache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Tache',
            new_name='tache_name',
        ),
    ]
